/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonPokemonRouteImport } from './routes/pokemon.$pokemon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonRoute = PokemonPokemonRouteImport.update({
  id: '/pokemon/$pokemon',
  path: '/pokemon/$pokemon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemon/$pokemon': typeof PokemonPokemonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemon/$pokemon': typeof PokemonPokemonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokemon/$pokemon': typeof PokemonPokemonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemon/$pokemon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemon/$pokemon'
  id: '__root__' | '/' | '/pokemon/$pokemon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonPokemonRoute: typeof PokemonPokemonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$pokemon': {
      id: '/pokemon/$pokemon'
      path: '/pokemon/$pokemon'
      fullPath: '/pokemon/$pokemon'
      preLoaderRoute: typeof PokemonPokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonPokemonRoute: PokemonPokemonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
